services:

    laravel-php:
        build: .docker/php
        volumes:
            - .:/var/www:cached

    laravel-nginx:
        image: nginx:latest
        ports:
            - 8123:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel-php
            - laravel-db

    laravel-db:
     image: postgres:16
     volumes:
         - .docker/postgres/data:/var/lib/postgresql/data
         - .docker/postgres/sql:/docker-entrypoint-initdb.d
     environment:
         - POSTGRES_USER=laravel_db_user
         - POSTGRES_PASSWORD=laravel_db_pass
         - POSTGRES_DB=laravel_db
